### ISSUE TITLE
Improving tutorial texts

### ISSUE THREAD

**Issue by paulgoetze** [cmusphinx/cmusphinx.github.io#31]
I’m currently reading the tutorial pages (starting with [concepts](https://cmusphinx.github.io/wiki/tutorialconcepts/)) and noticed that there are some parts that are a bit hard to understand because there are missing articles/words or missing punctuation in the sentences. Sometimes the sentence structure is a bit twisted, e.g.:

> **Word error rate.** Let we have original text and recognition text of length of N words. From them the I words were inserted D words were deleted and S words were substituted Word error rate is[...]

I'd like to help improving the reading experience a bit here and there, so if you think that’s a good idea,  I would just fix the text where I think it could be improved and open a PR for it while reading through the tutorials.

**Comment by nshmyrev** [comment]
Sure, please submit pull requests. That would be much appreciated.
