### ISSUE TITLE
Repeated heading and title in wiki pages.

### ISSUE THREAD

**Issue by saurabhshri** [cmusphinx/cmusphinx.github.io#35]
The page layout explicitly writes a title in h1 (see: https://github.com/cmusphinx/cmusphinx.github.io/blob/master/_layouts/page.html#L5) and then in all the wiki posts, the we have written the heading as well.

This causes the heading to appear twice.

![screen shot 2017-10-03 at 1 30 42 am](https://user-images.githubusercontent.com/12415700/31096696-81232020-a7da-11e7-9ba4-aa645f6456cc.png)

One of the following can be used to fix this : 

1. Manually change all the wiki pages as they were changed here : _(https://github.com/cmusphinx/cmusphinx.github.io/commit/bb5592040b0eab9294ed9567bdc1da9c516bbeed#diff-6c18a4b0709155468c72ee5846d8caf3R3 )_ . But this is long process, plus if in future we decide to move the pages, then again we'll have to write the headings from title.

2. Simply edit the page layout to remove the title. We can always have heading using the markdown syntax.

@nshmyrev Which one would you prefer for a PR?

**Comment by nshmyrev** [comment]
Sorry, I would prefer 1. It would not be that hard I suppose but we will be able to control the layout in a more centralized manner.

**Comment by saurabhshri** [comment]
@nshmyrev Sorry for going stale on the issue, for some reason, I didn't receive any email notification for this from Github.

I have made a PR, keeping point 1 in mind. :)
