### ISSUE TITLE
Example on website crashes

### ISSUE THREAD

**Issue by Moini** [cmusphinx/cmusphinx.github.io#40]
I've tried out the example given at https://cmusphinx.github.io/wiki/gstreamer/ (after fixing the missing parenthesis), and found it crashes with the very helpful message "Speicherzugriffsfehler (Speicherabzug geschrieben)" (segmentation fault) as soon as I click on the 'Speak' button.

It also prints out the attached parameters.

[output.txt](https://github.com/cmusphinx/cmusphinx.github.io/files/1613480/output.txt)

I'm on Linux Mint 18.3, and have installed and compiled lots of software, because originally, I wanted to try out pocketvox, but that depends on 'vader', which I read is no longer available, so I wanted to try something else. Let me know if you'd like to know anything specific about my system.

**Comment by Moini** [comment]
The reason was that I did not have the package pocketsphinx-en-us with the default language model, dictionary and acoustic model installed on my Linux Mint. Why isn't there a more helpful error message passed through to python?

**Comment by nshmyrev** [comment]
It is probably better to use python API without gstreamer.

**Comment by Moini** [comment]
Yes, I think you're right. 

It also seems that the gstreamer pocketsphinx plugin doesn't accept any other languages than English (I couldn't make it use **all** files from the hmm folder, it loaded most of them from the english model, and didn't accept setting these as properties for the gstreamer pocketsphinx object, which was very annoying) - finally worked around that by renaming my German files to us-en, replacing those in the /usr/share/pocketsphinx/models directory... 

Then, hooray, it also worked with German - while it was possible to 'just change' the files with the normal python bindings and using pyaudio (with a sample application, I really have no clue of how to use it yet). Really awkward... And a pity, because the gstreamer stuff looked a lot easier than pyaudio. I'm not a wizard, just playing around...

Anyway - if you don't recommend gstreamer, do you think it would make sense to open a bug report to 'please make an example app using pyaudio' (or whatever makes more sense)?

**Comment by nshmyrev** [comment]
> Anyway - if you don't recommend gstreamer, do you think it would make sense to open a bug report to 'please make an example app using pyaudio' (or whatever makes more sense)?

Only a pull request

You can also check https://github.com/gooofy/py-kaldi-asr, it is more accurate these days.

**Comment by Moini** [comment]
I think I'll rather try to fix pocketvox (https://github.com/benoitfragit/pocketVox), as it /almost/ works (well, at least I hope it only needs very little adjustments... I don't know any C, lol, but I can look up function definitions and read API docs) or maybe I'll start out from a half-working pyaudio example I've come across. If I get it to work, I could add a link to the the docs, or a copy of the example, if licence permits.

I'm not really concerned about accuracy, it's more playing around while I'm waiting for Mycroft (which also uses pocketsphinx for keyword detection, as far as I understand) to get support for DeepSpeech for the more complex talking :) .

Kaldi documentation is hard to understand for me. It doesn't look like something that is good for beginners. And I don't want a client-server architecture, just read directly from microphone, but it looks like that's not part of the package...

Anyway, thanks for replying!
