### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by Pankaj-Baranwal** [cmusphinx/cmusphinx.github.io#8]
So, the entire night, I have been going through the documentation of Pocketsphinx for a project I am working on and whenever i find a missing link (probably due to shift from sourceforge to github), I am creating a pull request with the correct one.
But I could not find the correct redirection URL for https://cmusphinx.github.io/api/pocketsphinx/
The original link used to be: http://cmusphinx.sourceforge.net/api/pocketsphinx/
Where are these api files hosted in github?

**Comment by nshmyrev** [comment]
API docs are in /doc, I fixed the links too, should be better now.
